name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - id: foo
      uses: hello-world-composite-action@v1
      with:
        who-to-greet: 'Mona the Octocat'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: demo
        path: ${{ github.workspace }}//**
      
