name: check-secrets
on:
    push:
        branches:
            - main
    pull_request:
jobs:
    check-secrets:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Git Secrets
              run: |
                  sudo apt-get install git-secrets

            - name: Scan for secrets
              run: git secrets --scan
